# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=30, verbose_name='\u90e8\u95e8')),
                ('work_num', models.CharField(blank=True, max_length=30, verbose_name='\u5de5\u53f7')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='\u59d3\u540d')),
                ('wx_openid', models.CharField(blank=True, max_length=30, verbose_name='wx_openid')),
                ('wx_nickname', models.CharField(blank=True, max_length=100, verbose_name='wx\u6635\u79f0')),
                ('sex', models.CharField(blank=True, choices=[('0', '\u7537'), ('1', '\u5973')], max_length=2, verbose_name='\u6027\u522b')),
                ('working_years', models.IntegerField(verbose_name='\u5de5\u4f5c\u5e74\u9650')),
                ('company_working_years', models.IntegerField(verbose_name='\u4f01\u4e1a\u5de5\u4f5c\u5e74\u9650')),
                ('vacation_days', models.IntegerField(default=5, verbose_name='\u5e74\u5047\u6570')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wechat_user.WXUser', verbose_name='\u9886\u5bfc')),
            ],
        ),
    ]
