# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='cell_phone',
            field=models.CharField(default=2, max_length=20, verbose_name='\u624b\u673a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='work_num',
            field=models.CharField(max_length=30, verbose_name='\u5de5\u53f7'),
        ),
    ]
