# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0003_auto_20151123_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxuser',
            name='vacation_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='refuse_reason',
            field=models.TextField(blank=True, verbose_name='\u62d2\u7edd\u539f\u56e0'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='company_vacation_days',
            field=models.IntegerField(default=0, verbose_name='\u4f01\u4e1a\u5e74\u5047\u6570'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='legal_vacation_days',
            field=models.IntegerField(default=5, verbose_name='\u6cd5\u5b9a\u5e74\u5047\u6570'),
        ),
    ]
