# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0005_auto_20151221_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='deal_end_time',
            field=models.DateTimeField(null=True, verbose_name='\u5ba1\u6279\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
