# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0006_auto_20151221_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='\u90ae\u7bb1'),
            preserve_default=False,
        ),
    ]
