# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0010_auto_20151223_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.IntegerField(choices=[('0', '\u5e74\u5047'), ('1', '\u4e8b\u5047'), ('2', '\u75c5\u5047'), ('3', '\u4ea7\u5047'), ('4', '\u4f1a\u8bae'), ('5', '\u57f9\u8bad'), ('6', '\u51fa\u5dee'), ('7', '\u5176\u4ed6')], verbose_name='\u5177\u4f53\u7c7b\u522b'),
        ),
    ]
