# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0012_auto_20151224_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attach_photo',
            field=models.TextField(blank=True, verbose_name='\u4e0a\u4f20\u9644\u4ef6\u56fe\u7247'),
        ),
    ]
